### ISSUE TITLE
generic-battery-card

### ISSUE THREAD

**Issue by iboboc** [Codegnosis/givtcp-battery-card#25]
Any chance to make this card generic, for any battery entity?

Basically the same layout and graphic but make the input data to be selected by user, choosing the entities for each value (Soc, power, energy, etc). This will allow anyone to use the card with a custom battery.

Thanks.

**Comment by Codegnosis** [comment]
Hi! Thanks for the feature request. Unfortunately, this would probably require an enormous amount of work and code refactoring because all of the battery statistics (SOC, charge/discharge/power etc.) are derived automatically using a single sensor entity specified in the config. This single entity is used to find all the respective sensor data from GivTCP and as such there are no config values for each individual sensor.

Sorry :)
